##############################################################################
#                                NAMESPACE                                   #
##############################################################################
apiVersion: v1
kind: Namespace
metadata:
  name: justaml
---
##############################################################################
#                                   REDIS                                    #
##############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: justaml
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2.1-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: justaml
spec:
  ports:
    - name: http
      port: 6379
      targetPort: 6379
  selector:
    app: redis
---
##############################################################################
#                         INGRESS+DEPLOYMENTS                                #
##############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: justaml
  namespace: justaml
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  selector:
    matchLabels:
      app: justaml-app
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: justaml-app
    spec:
      volumes:
        - name: justaml-vol-data
          hostPath:
            path: /storage/justaml/data
        - name: justaml-vol-uploads
          hostPath:
            path: /storage/justaml/uploads
      containers:
        - name: app
          image: mustakimali/justaml:220619_1727
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: justaml-vol-data
              mountPath: /app/App_Data
            - name: justaml-vol-uploads
              mountPath: /app/wwwroot/upload
          env:
            # Hosting Options
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"

            - name: ASPNETCORE_URLS
              value: "http://*:3000"

            # Application Option
            - name: "Sentry__Dsn"
              valueFrom:
                secretKeyRef:
                  name: "justaml-secret"
                  key: "sentry_dsn"

            # use redis for data+bg jobs storage & signalr backplane
            - name: "RedisCache"
              value: "redis-service:6379,defaultDatabase=0"

          livenessProbe:
            httpGet:
              path: /api/test
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/test
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              memory: "128M"
              cpu: "256m"
            limits:
              memory: "512M"
              cpu: "512m"
---
##############################################################################
#                                  SERVICE                                   #
##############################################################################
apiVersion: v1
kind: Service
metadata:
  name: justaml-service
  namespace: justaml
spec:
  ports:
    - name: https
      port: 80
      targetPort: 3000
  selector:
    app: justaml-app
---
##############################################################################
#                                  INGRESS                                   #
##############################################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: justaml-ingress
  namespace: justaml
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  tls:
  - hosts:
    - tnxfr.com
  backend:
    serviceName: justaml-service
    servicePort: 80
  rules:
    - host: tnxfr.com
---
# redirect from justa.ml to tnxfr.com
 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: justaml-ingress-redirect
   namespace: justaml
   annotations:
     nginx.ingress.kubernetes.io/server-snippet: |
       server_name justa.ml;
       return 301 $scheme://tnxfr.com$request_uri;
 spec:
   tls:
     - hosts:
         - justa.ml
   rules:
     - host: justa.ml
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: justaml-hpa
  namespace: justaml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: justaml
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 120
